mongoexport --db cnj --collection justica_eleitoral_filter --out "C:\base-cnj\justica_eleitoral.json"
mongoexport --db cnj --collection justica_estadual_filter  --out "C:\base-cnj\justica_estadual.json"
mongoexport --db cnj --collection justica_federal_filter --out "C:\base-cnj\justica_federal.json"
mongoexport --db cnj --collection justica_militar_filter  --out "C:\base-cnj\justica_militar.json"
mongoexport --db cnj --collection justica_trabalho_filter --out "C:\base-cnj\justica_trabalho.json"
